default_stages:
  - commit

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]

      # Run the formatter.
      - id: ruff-format


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
        exclude: ^\.vscode/
      - id: check-yaml
        exclude: mkdocs\.yml$
      - id: check-symlinks
