# Project information
site_name: Today I Learned          # Required: Sets the name of the documentation site
site_author: Malcolm Jones          # Sets the author meta tag in the HTML header
site_description: >-                # Sets the site description meta tag in the HTML header
  A collection of notes on things I've learned.
edit_uri: edit/main/docs           # Configures the edit button URL path
watch:                             # Additional directories to watch when running mkdocs serve
  - src/

# Repository information
repo_name: malcolmjones/til        # Sets the name displayed for the repository link
repo_url: https://github.com/malcolmjones/til  # URL to the repository

# Copyright footer text
copyright: Copyright &copy; 2024 Malcolm Jones - All Rights Reserved

# Additional CSS files to include
extra_css:
- css/mkdocstrings.css

# Theme configuration
theme:
  name: material                    # Uses the Material for MkDocs theme
  features:
    - content.action.edit          # Adds an edit button to pages
    - content.action.view          # Adds a view source button
    - content.code.copy           # Adds a copy button to code blocks
    - content.code.select         # Enables code block text selection
    - content.tooltips            # Enables tooltip annotations
    - navigation.footer           # Shows footer navigation
    - search.share               # Enables search result sharing

# Plugin configuration
plugins:
  - autorefs                      # Enables automatic cross-references
  - mermaid2                     # Enables Mermaid.js diagrams support
  - mkdocstrings:                # Python API documentation generator
      handlers:
        python:
          import:                # External documentation inventory files
          - https://docs.python.org/3/objects.inv
          - https://installer.readthedocs.io/en/stable/objects.inv
          - https://mkdocstrings.github.io/autorefs/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]      # Exclude private members
            heading_level: 1
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
      default_handler: python
  - search                       # Enables the search feature
  - tags                         # Enables tags/categories for pages

# Markdown extension configuration
markdown_extensions:
  # Python Markdown
  - toc:                         # Table of contents extension
      permalink: true            # Adds permalinks to headers

  # Python Markdown Extensions
  - abbr                         # Abbreviation syntax support
  - admonition                   # Adds note/warning/etc blocks
  - attr_list                    # Enables custom attributes
  - pymdownx.details            # Collapsible admonition blocks
  - pymdownx.emoji:             # Emoji support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight          # Code syntax highlighting
  - pymdownx.inlinehilite       # Inline code highlighting
  - pymdownx.magiclink          # Auto-links URLs in text
  - pymdownx.snippets           # Include content from other files
  - pymdownx.superfences:       # Enhanced fenced code blocks
      custom_fences:            # Custom fence types
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:            # Tabbed content
      alternate_style: true
  - tables                      # Table syntax support
